Add back button to appbar and button section
Samsung/TAU pull request #1304
Opened 2020-07-14 14:48 UTC by korneliakobiela

[Issue] #1188
[Problem] [UiComponents] App doesn't have back button in every place.
[Solution] - Add backbutton to sections Appbar and Button

Signed-off-by: Kornelia Kobiela <korneliak.95@gmail.com>

2020-07-15 00:25 UTC, HunseopJeong approved these changes
LGTM

2020-07-15 05:13 UTC, lslachciak requested changes
Please check my comments in code,
also I see missing back button in following submenus
examples/mobile/UIComponents/components/toast/index.html
examples/mobile/UIComponents/components/textfields/index.html
examples/mobile/UIComponents/components/etc/index.html
examples/mobile/UIComponents/components/etc/interactive/index.html
examples/mobile/UIComponents/components/etc/graphs/index.html

2020-07-15 05:13 UTC, lslachciak commented on examples/mobile/UIComponents/components/buttons/contained/index.html
> +		</div>
please double check code here, view is broken in this example
![image](https://user-images.githubusercontent.com/2246331/87505524-5baab000-c669-11ea-8204-14c9702241a1.png)

2020-07-15 05:13 UTC, lslachciak commented on examples/mobile/UIComponents/components/appbar/multiline/multiline-title.html
> +			<div class="ui-appbar-left-icons-container">
we need to decide and be consistent if we add back button to submenus or examples too.
This is example not submenu.
If we add back button to examples we will need to add to all of them
e.g. also
examples/mobile/UIComponents/components/etc/units/units.html
examples/mobile/UIComponents/components/etc/units/fonts.html
examples/mobile/UIComponents/components/etc/interactive/coverflow/index.html
examples/mobile/UIComponents/components/etc/interactive/interactive3D/index.html
examples/mobile/UIComponents/components/etc/about/index.html

2020-07-15 05:13 UTC, lslachciak commented on examples/mobile/UIComponents/components/appbar/multiline/subtitle.html
>  		<header>
ditto.

2020-07-15 05:13 UTC, lslachciak commented on examples/mobile/UIComponents/components/buttons/contained/body-area/2-buttons.html
> +		<header>
ditto.

2020-07-17 13:02 UTC, lslachciak approved these changes
seems good.
Toast, Checkbox and Etc main menu will need back button in other PR

2020-07-20 07:44 UTC, merged