(wearable) Selector: fix for scale active item
Samsung/TAU pull request #389
Opened 2019-09-15 08:18 UTC by TomaszLukawskiSam

[Issue] https://github.com/Samsung/TAU/issues/369
[Problem] Option menu icons disappearing on Gear S3
[Solution] Is possible that some devices convert number values
 into string using number format specific for localization region.
 The fix prevents to use comma for decimal places.

Signed-off-by: Tomasz Lukawski <t.lukawski@samsung.com>

2019-09-15 10:16 UTC, martijnvankekem commented
As the OP, I'll check tonight if this fix worked, but because It's basically the same as my 'hack', just executed prettier, I think it will work. You'll hear from me!

2019-09-15 19:28 UTC, martijnvankekem requested changes
Unfortunately, this doesn't work. Hang tight, because I did figure out what the problem is and how it could/should be solved

The following things were discovered by me during testing.
1. The string itself, that is concatenated, DOES contain the right decimal place.
2. The problem is not in the concatenation of the strings, it goes wrong upon requesting the current transform tag. When you set the element's scale manually to `0.8235` in the console, and after that request the transform tag by entering `[element].style.transform`, the decimal place IS replaced.
3. This problem ONLY occurs when your watch is using a display language that uses a comma for its decimal places (for example, when my watch is set to English, this problem doesn't occur, but is does when it's set to Dutch).

With other words, the `.replace` tag isn't doing anything because `scale(0.8235)` isn't found in the `[element].style.transform`, because that string contains the `scale(0,8235)`.

2019-09-15 22:51 UTC, martijnvankekem commented
See #391

2019-09-25 07:40 UTC, TomaszLukawskiSam commented
> See #391

I'm during verification of your solution for this issue.

2019-09-27 12:04 UTC, TomaszLukawskiSam commented
The patch is ineffective.

2019-09-27 12:04 UTC, closed without merging