(wearable) Selector: fix for scale active item
Samsung/TAU pull request #391
Opened 2019-09-15 19:42 UTC by martijnvankekem

[Issue] #369
[Problem] Upon retrieval of the string after calling .style.transform, the decimal place is replaced by a comma if the watch is set to a display language that uses commas for decimal places.
[Solution] Replace the decimal place comma by a dot.

Improvement (or actually working solution) for #389

2019-09-25 08:24 UTC, TomaszLukawskiSam approved these changes
The patch doesn't looks beautiful but works good. I can accept this changes as hot fix but the issue has to be fix more agile.

2019-09-25 08:26 UTC, TomaszLukawskiSam requested changes
Can you organize your PR and complete commit message?

2019-09-25 14:16 UTC, martijnvankekem commented
@TomaszLukawskiSam what do you want me to organize exactly?

2019-09-25 14:48 UTC, TomaszLukawskiSam commented
> @TomaszLukawskiSam what do you want me to organize exactly?

Squash the commits to one commit with nice commit message like other commits.

2019-09-26 07:31 UTC, martijnvankekem commented
See #408, a much better solution, didn't think of that.

2019-09-26 07:31 UTC, closed without merging