[Wearable] Fix selector icons disappearing
Samsung/TAU pull request #408
Opened 2019-09-26 07:23 UTC by ampanasiuk

[Issue] https://github.com/Samsung/TAU/issues/369
[Problem] updating style.transform with single-arg scale() value in js
          makes the decimal point replaced with comma, at least on
          some locales
[Solution] use two-arg style.transform scale() value

2019-09-26 08:33 UTC, ampanasiuk commented
This works in that icons don't disappear, but sadly retrieving style.transform has "scale(0,8235, 0,8235)" and this doesn't work with "d = b.replace(w.ITEM_NORMAL_SCALE, w.ITEM_ACTIVE_SCALE)", so the active item's size is not increased.

2019-09-26 09:17 UTC, ampanasiuk commented
New approach

2019-09-27 12:12 UTC, TomaszLukawskiSam requested changes
Hi, These changes you should do in `src/js/profile/wearable/widget/wearable/Selector.js`
The `dist` folder is replaced during build process.

2019-09-29 09:54 UTC, TomaszLukawskiSam approved these changes

2019-09-29 09:57 UTC, TomaszLukawskiSam requested changes
Hi, would you change the PR to branch `tau_1.0`?

2019-09-30 07:23 UTC, TomaszLukawskiSam approved these changes

2019-09-30 07:24 UTC, merged