[Wearable] Replace "change" event with "input" for Slider
Samsung/TAU pull request #448
Opened 2019-10-09 07:08 UTC by grzegorz-czajkowski

[Issue] N/A

[Problem] Mobile profile successfully emits both events
	"input" and "change" on Slider widget whereas Wearable profile
	emits only "change".

[Solution] Emits "input" event instead of "change" since according to [1]
	input event should be fired immediately when the slider is adjusted but
	change event does not fire immediately, the value does not change until
	the slider stops moving
	This fixes SThing.js behaviour with Slider and Dimmer synchronization
	for Wearable.

[Remarks] May cause regression for tau apps already using "change" event.
	To fix this we should provide real implementation for "change" event.

[1] https://www.impressivewebs.com/onchange-vs-oninput-for-range-sliders/

Signed-off-by: Grzegorz Czajkowski <g.czajkowski@samsung.com>

2019-10-09 08:19 UTC, lslachciak requested changes
@grzegorz-czajkowski please make sure that CHANGE is not used by UIComponents.
After check, I'll approve

2019-10-09 08:27 UTC, pkaczmarczy commented
The change event is used in tau 1.1 wearable dimmer sample.
I think we should trigger both events.

IMO change event should be triggered after user release the slider handle and value changes, and input event should be triggered with each handle movement.

2019-10-09 08:36 UTC, grzegorz-czajkowski commented
@lslachciak 
"change" event is being used by
examples/wearable/UIComponents/contents/controls/slider/extended_slider.js
in both tau 1.0 and 1.1.
I will fix this.

@pkaczmarczy 
Where I can find source of  tau 1.1 wearable dimmer sample?
>>  I think we should trigger both events.
They behave slightly different, if someone needs "change" event we should implemented it according to spec.

2019-10-09 09:15 UTC, lslachciak approved these changes

2019-10-09 09:18 UTC, lslachciak commented
> 
> 
> The change event is used in tau 1.1 wearable dimmer sample.
> I think we should trigger both events.
> 
> IMO change event should be triggered after user release the slider handle and value changes, and input event should be triggered with each handle movement.
@pkaczmarczy 
I think we can create new issue for change event implementation in future version of TAU not blocking this one. OK?

2019-10-09 11:30 UTC, pkaczmarczy commented
Yes, I think we should fix event emitting for slider.
@grzegorz-czajkowski The dimmer sample is available only on tau_1.1 branch and file path is: examples/wearable/UIComponents/contents/controls/dimmer.js

2019-10-09 11:43 UTC, grzegorz-czajkowski commented
@pkaczmarczy Ok thanks. I will prepare separate PR to fix this.

2019-10-11 06:13 UTC, grzegorz-czajkowski commented
@lslachciak  and @pkaczmarczy 
Created issue to add "change" event - https://github.com/Samsung/TAU/issues/453
Patch to tau 1.1 is here https://github.com/Samsung/TAU/pull/449

2019-10-11 09:24 UTC, TomaszLukawskiSam requested changes
In my opinion issue #453 is blocking for this PR

2020-05-07 05:25 UTC, grzegorz-czajkowski commented
This needs improvements and is out of scope currently.

2020-05-07 05:25 UTC, closed without merging