Marquee: fix for wrong marquee position after reset
Samsung/TAU pull request #492
Opened 2019-11-25 15:31 UTC by TomaszLukawskiSam

[Issue] https://github.com/Samsung/TAU/issues/489
[Problem] Marquee: wrong marquee postion after reset & (re)start widget
[Solution] Animation reset has been implemented

Signed-off-by: Tomasz Lukawski <t.lukawski@samsung.com>

2019-11-27 10:02 UTC, pkaczmarczy requested changes

2019-11-27 10:02 UTC, pkaczmarczy commented on src/js/core/widget/core/Marquee.js
> +					"" : "-webkit-linear-gradient(left, #ffffff 0, #ffffff 85%, transparent 100%)";
Could you please use gradient style settings from GRADIENTS object?

2019-11-27 10:02 UTC, pkaczmarczy commented on src/js/core/util/animation/animation.js
> +					// reset durring animation
durring -> during

2019-11-27 10:02 UTC, pkaczmarczy commented on src/js/core/util/animation/animation.js
> +			function resetStartTimeForAnimateConfig(animateConfig) {
I am getting the exception during scrolling on device:
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at resetStartTimeForAnimateConfig (tau.js:18923)
    at Animate.prototype.reset (tau.js:18943)
    at Marquee.prototype.reset (tau.js:19711)
    at Listview.prototype._onChange (tau.js:32417)
    at Listview.prototype.handleEvent (tau.js:32683)
    at Object.trigger (tau.js:1273)
    at Listview.prototype.trigger (tau.js:8119)
    at Listview.prototype._rollDown (tau.js:32075)
    at Listview.prototype._onRotary (tau.js:32133)

2019-11-27 15:30 UTC, pkaczmarczy requested changes
After callining

widget.reset(); widget.stop(); synchronously one after another Marquee does not reset.
If called in widget.stop() then widget.reset() everything is fine

2019-11-27 22:01 UTC, lslachciak commented on src/js/core/util.js
> +			 * @param {*} animationId value for identify animation in quee
typo "quee" -> queue

2019-11-27 22:04 UTC, lslachciak commented
@singa2000,  looks like we still need to make some improvements, sorry can't make release today

2019-11-28 07:58 UTC, TomaszLukawskiSam commented on src/js/core/util.js
> +			 * @param {*} animationId value for identify animation in quee
Fixed.

2019-11-28 09:31 UTC, TomaszLukawskiSam commented
> After callining
> 
> widget.reset(); widget.stop(); synchronously one after another Marquee does not reset.
> If called in widget.stop() then widget.reset() everything is fine

Fixed.

2019-11-28 10:16 UTC, pkaczmarczy approved these changes
Looks good to me.

2019-11-28 10:39 UTC, merged