Fix the problem that cannot build widget with one or none items
Samsung/TAU pull request #540
Opened 2020-01-12 12:31 UTC by HunseopJeong

[Issue] #477
[Problem] Scroller is not assigned when the item is one or none
[Solution] Assign the body element when there is no scrollable parent

Signed-off-by: Hunseop Jeong <hs85.jeong@samsung.com>

2020-01-13 10:48 UTC, TomaszLukawskiSam requested changes

2020-01-13 10:48 UTC, TomaszLukawskiSam commented on src/js/profile/wearable/widget/wearable/SnapListview.js
> +				scroller = getScrollableParent(listview) || ui.page;
I have suggestion to this code. The standard scrolling layer is the element with class "ui-scroller". This element is created during build process of page.
```
scroller = getScrollableParent(listview) ||
    **ui.page.querySelector(".ui-scroller")** ||
    ui.page;
```

2020-01-13 10:54 UTC, singa2000 commented
In my test,  the issue  is reproduced SnapList  has just no item.
If  it has one item, there is no problem.
But after the PR, if there is no list but it can  scroll by touch and it's not good behavior.

2020-01-13 10:59 UTC, TomaszLukawskiSam commented
> In my test, the issue is reproduced SnapList has just no item.
> If it has one item, there is no problem.
> But after the PR, if there is no list but it can scroll by touch and it's not good behavior.

I agree with you. The PR didn't resolve all issue with empty snaplistview.
like: 

> Uncaught TypeError: Cannot read property 'position' of undefined
>     at getSnapPointIndexByScrollPosition (tau.js:16124)
>     at touchEndCalculateSpeed (tau.js:16168)
>     at HTMLDocument.touchEnd (tau.js:16224)
> getSnapPointIndexByScrollPosition @ tau.js:16124
> touchEndCalculateSpeed @ tau.js:16168
> touchEnd @ tau.js:16224

2020-01-14 08:58 UTC, HunseopJeong commented
@TomaszLukawskiSam,

2020-01-20 11:53 UTC, TomaszLukawskiSam approved these changes
Verified. Works good but we need also changes for a use case that developer want to add new item to list.
```
var l = tau.engine.getBinding(snaplistElement),
     li = document.createElement('li');

li.innerHTML = "aaaaaaaaaaaa";
l.element.appendChild(li);
l.refresh();
```

This can be done by another PR.
Patch for this may looks like this https://github.com/TomaszLukawskiSam/TAU/tree/add-item-to-snaplistview

2020-01-22 12:18 UTC, HunseopJeong commented
@TomaszLukawskiSam,
Okay. After merging this PR, please make a PR for the proposed use case.
I think we would be good to add a new API for the 'addItem'.

2020-01-22 12:18 UTC, merged