Marquee: fix infinite animation
Samsung/TAU pull request #545
Opened 2020-01-14 15:39 UTC by gwolny

[Issue] N/A
[Problem] Infinite animation is running only for one iteration.
[Solution] Change "iteration" type to "string". When using string both
number and "infinite" are parsed correctly.

Signed-off-by: Grzegorz Wolny <g.wolny@samsung.com>

2020-01-15 07:35 UTC, lslachciak requested changes
Besides style errors reported by Travis
I think you should check if parseInt returns NaN
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/parseInt

2020-01-15 13:56 UTC, gwolny commented
Before the patch if not a number string was given, it was always converted to the NaN. With the patch string "infinite" is correctly handled. Other are converted to the NaN. So for other cases it works as before.

2020-01-15 14:04 UTC, lslachciak approved these changes

2020-01-15 14:04 UTC, lslachciak commented
please wait with merge

2020-01-20 09:26 UTC, TomaszLukawskiSam requested changes

2020-01-20 09:26 UTC, TomaszLukawskiSam commented on .eslintrc.js
> +		"equal": false,
This is not general true. The "equal" and "test" are only in tests.

Better solution is define
`/* global equal, test */` in specific file
or better modify `/*global test */` and modify test like:
```
	test("API of core Marquee Widget", function (assert) {
             assert.equal( ... );
     ...   
```

2020-01-21 12:23 UTC, TomaszLukawskiSam approved these changes
Looks good to me.

2020-01-23 09:27 UTC, merged