Marquee runtime iteration
Samsung/TAU pull request #554
Opened 2020-01-17 11:14 UTC by gwolny

2020-01-17 11:18 UTC, gwolny commented
This patch depends on #554 
Only last commit is a subject of this review.

2020-01-20 10:04 UTC, TomaszLukawskiSam commented
> This patch depends on #554
> Only last commit is a subject of this review.

You mean #545

2020-01-20 10:06 UTC, TomaszLukawskiSam approved these changes
The patch works good but some issues are in PR #545

2020-01-20 10:07 UTC, TomaszLukawskiSam requested changes
Please fix issue in PR #545

2020-01-21 12:24 UTC, TomaszLukawskiSam commented
This PR needs rebase.

2020-01-22 08:11 UTC, TomaszLukawskiSam approved these changes

2020-01-23 09:51 UTC, merged