Reposition sections when setActiveSection API is called by app creator
Samsung/TAU pull request #687
Opened 2020-03-03 12:34 UTC by lslachciak

[Issue] https://github.com/Samsung/TAU/issues/659
[Problem] When calling setActiveSection API directly in app, in case of swipe strange animation occurs
[Reason] Normally _repositionSections method is called when widget is initialized.
When ui-section-active not set all sevalues will be initialized with default ones.
When developers calls setActiveSection directly method _repositionSections is not called

[Solution] Call _repositionSections inside setActiveSection

Signed-off-by: Lukasz Slachciak <l.slachciak@samsung.com>

2020-03-04 10:04 UTC, TomaszLukawskiSam requested changes

2020-03-04 10:04 UTC, TomaszLukawskiSam commented on src/js/core/widget/core/SectionChanger.js
> +				setActiveSection: function (index, duration, direct, reposition) {
Please add js doc for `reposition`.

2020-03-04 15:02 UTC, lslachciak commented on src/js/core/widget/core/SectionChanger.js
> +				setActiveSection: function (index, duration, direct, reposition) {
done

2020-03-05 08:09 UTC, TomaszLukawskiSam approved these changes

2020-03-17 22:56 UTC, HunseopJeong approved these changes
LGTM

2020-03-17 22:56 UTC, merged