Fonts: fix for font definition
Samsung/TAU pull request #812
Opened 2020-03-24 08:49 UTC by TomaszLukawskiSam

[Issue] N/A
[Problem] Medium font is too bold
[Solution] Font definition has been fixed

Signed-off-by: Tomasz Lukawski <t.lukawski@samsung.com>

2020-03-24 08:53 UTC, HunseopJeong approved these changes
I think it too bold.

2020-03-24 08:58 UTC, lslachciak commented on src/css/profile/mobile/fonts.less
> +    font-family: sec-roboto-light;
according to the MDN font-family
Specifies a name that will be used as the font face value for font properties.
if we have two the same font-family names how we can differentiate them?

2020-03-24 09:01 UTC, lslachciak commented on src/css/profile/mobile/common/tizen.less
> +	font-family: sec-roboto-light;
I though that sec-robot-light is alternative font if the Roboto-Medium is not available

2020-03-24 09:10 UTC, lslachciak requested changes
I have doubt regarding this PR.
I think that we should clarify with UX first:
1. Does Roboto Medium should have bold style? If yes, why in guides when Roboto MEdium is used font is not bold?
2. What should be priority
sec
roboto light over Roboto Regular.ttf when exist in system?
roboto light

2020-03-24 10:03 UTC, HunseopJeong commented
It used the origin medium in subheader
![image](https://user-images.githubusercontent.com/29908741/77412897-e7ba7280-6e01-11ea-99ab-638582c2efe8.png)

It is the subheader image at UX guide (6-6)
![image](https://user-images.githubusercontent.com/29908741/77413028-11739980-6e02-11ea-951e-6e61d0414267.png)

It seems to be different in my eyes... :(

2020-03-24 10:12 UTC, singa2000 commented
@HunseopJeong 
OK.
As I see,  Roboto Medium should have bold style and the he GUI Guide screenshot also use the bold style.
But it different look as you told.
I will check it.

2020-03-25 05:47 UTC, singa2000 commented
I checked about the font.

1. When we use "Roboto Medium", we should not  put the "font-weight: bold"
    Would you just remove the "font-weight", please?

    .font(medium) {
	font-family: Roboto-Medium, sec-roboto-light;
	_font-weight: bold;_
}

2. About the font-family like "sec-xx" , we don't need to consider it.

2020-03-25 08:31 UTC, lslachciak commented
@TomaszLukawskiSam I agree with @singa2000 lets remove 
font-weight: bold;

2020-03-25 09:02 UTC, TomaszLukawskiSam commented
> @TomaszLukawskiSam I agree with @singa2000 lets remove
> font-weight: bold;
> and
> "sec-xx

I updated PR.

2020-03-25 11:27 UTC, HunseopJeong approved these changes
LGTM

2020-03-25 11:30 UTC, lslachciak approved these changes
Buttons now looks much better, verified

2020-03-25 11:32 UTC, merged