Fix to calculate the height of the Spin widget
Samsung/TAU pull request #909
Opened 2020-04-08 04:26 UTC by HunseopJeong

[Issue] https://github.com/Samsung/TAU/issues/900
[Problem] The getBoundingClientRect() returns the '0' for the height of containerRect
[Solution] Modify the calculation for the containerHeight to get the defined height on the css style

Signed-off-by: Hunseop Jeong <hs85.jeong@samsung.com>

2020-04-08 05:03 UTC, HunseopJeong commented
![image](https://user-images.githubusercontent.com/29908741/78746423-c3ce6380-79a1-11ea-8833-0a1e475cb637.png)

2020-04-08 09:45 UTC, TomaszLukawskiSam commented on src/js/profile/mobile/widget/TimePicker.js
> +					self._spins[key]._refresh();
This works good but you use '@protected' method of widget. Please use 'refresh' instead of  `_refresh`.

2020-04-08 09:56 UTC, TomaszLukawskiSam requested changes
Patch works good. One minor issue.

2020-04-09 07:55 UTC, DohyungLim reviewed
1 comment check and other code is looks good.

2020-04-09 07:55 UTC, DohyungLim commented on src/js/core/widget/core/Spin.js
> +					self._containerHeight
semicolon required.

2020-04-10 09:55 UTC, HunseopJeong commented
@TomaszLukawskiSam,
Could you review this PR again?

2020-04-10 10:26 UTC, TomaszLukawskiSam approved these changes
Looks good to me.

2020-04-10 10:28 UTC, merged